// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CopyLink: typeof import('./src/components/CopyLink.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconLink: typeof import('./src/components/IconLink.vue')['default']
    MainNav: typeof import('./src/components/MainNav.vue')['default']
    PasteLink: typeof import('./src/components/PasteLink.vue')['default']
    PhraseCard: typeof import('./src/components/PhraseCard.vue')['default']
    RadioGroup: typeof import('./src/components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendPreview: typeof import('./src/components/SendPreview.vue')['default']
    SwapPreview: typeof import('./src/components/SwapPreview.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    TokenSelect: typeof import('./src/components/TokenSelect.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
  }
}

export {}
